---
version: '3'
services:
  db:
    image: mariadb:10.5.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
    ports:
      - '33061:3306'
    volumes:
      - issp_db_data:/var/lib/mysql
  app:
    depends_on:
      - db
    build: .
    ports:
      - '3001:3000'

volumes:
  issp_db_data:
