name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root@localhost:3306/nurse_joy_testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: npm install
      # Create the database
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npm run test
