name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      DATABASE_URL: mysql://root@127.0.0.1:3309/nurse_joy_testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: npm install
      # Create the database
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npm run test
