name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
          cache: 'npm'
      - run: npm install
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npm run test
        env:
          DATABASE_URL: mysql://root:password@127.0.0.1:32574/nurse_joy_testing
