name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/nurse_joy_testing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: rm -rf prisma/migrations
      - run: sed -ie 's/mysql/postgresql/g' prisma/schema.prisma
      - run: npm install
      # Create the database
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - run: npm run test
